[config]
response_language = "pt-BR"
output_relevant_configurations = true
publish_output=true
enable_custom_labels = true
max_description_tokens = 800
add_repo_metadata = true
add_repo_metadata_file_list = ["changelog.md", "README.md"]

[pr_reviewer]
enable_review_labels_effort = true
enable_review_labels_security = true
enable_auto_approval = false
require_focused_review = true
require_estimate_effort_to_review = true

[pr_description]
enable_pr_type = true
enable_pr_diagram = false
add_original_user_description = true
use_bullet_points = true

[custom_labels."Frontend Vue.js"]
description = "Mudanças na interface Vue.js do sistema de visualização"

[custom_labels."API Spring Boot"]
description = "Mudanças na API Java/Spring Boot"

[custom_labels."Airflow ETL"]
description = "Mudanças nos pipelines de dados do Airflow"

[custom_labels."Database Migration"]
description = "Mudanças no esquema do banco via Flyway"

[custom_labels."REDS Critical"]
description = "Mudanças críticas no sistema REDS que afetam dados de saúde"

[custom_labels."Patient Data"]
description = "Mudanças que envolvem dados de pacientes - requer revisão de privacidade"

[custom_labels."Security Healthcare"]
description = "Mudanças relacionadas à segurança de dados de saúde"

[custom_labels."Performance ETL"]
description = "Otimizações de performance nos pipelines de dados"

[custom_labels."LGPD Compliance"]
description = "Mudanças relacionadas à conformidade com LGPD"

[custom_labels."ETL Pipeline"]
description = "Mudanças nos pipelines de ETL de dados de saúde"

[custom_labels."Data Quality"]
description = "Validações e qualidade de dados"

[custom_labels."API Endpoint"]
description = "Novos endpoints ou mudanças em endpoints existentes"

[custom_labels."Security API"]
description = "Mudanças relacionadas à segurança da API"

[custom_labels."Data Model"]
description = "Mudanças nos modelos de dados"

[custom_labels."Performance API"]
description = "Otimizações de performance na API"

[custom_labels."Schema Change"]
description = "Mudanças na estrutura do banco de dados"

[custom_labels."Data Migration"]
description = "Migração de dados existentes"

[custom_labels."Performance DB"]
description = "Otimizações de performance no banco"

[custom_labels."Rollback Safe"]
description = "Migration com estratégia de rollback segura"

[custom_labels."UI Component"]
description = "Novos componentes ou mudanças em componentes existentes"

[custom_labels."UX Improvement"]
description = "Melhorias na experiência do usuário"

[custom_labels."Accessibility"]
description = "Implementações de acessibilidade"

[custom_labels."Performance Frontend"]
description = "Otimizações de performance no frontend"
