[config]
response_language = "pt-BR"
enable_custom_labels = true
max_description_tokens = 800
add_repo_metadata = true
add_repo_metadata_file_list = ["changelog.md", "README.md"]

[pr_reviewer]
enable_review_labels_effort = true
enable_review_labels_security = true
enable_auto_approval = false
require_focused_review = true
require_estimate_effort_to_review = true
extra_instructions = """
CONTEXTO CRÍTICO: Sistema de saúde (REDS).
Comece as frases com EDS no ínicio.

PRIORIDADES DE REVISÃO:
1. Segurança e privacidade de dados de pacientes (LGPD)
2. Integridade de dados de saúde
3. Performance em sistemas de grande volume
4. Conformidade regulatória de saúde
5. Usabilidade para profissionais de saúde

VERIFICAÇÕES OBRIGATÓRIAS:
- Dados sensíveis não expostos em logs
- Validação adequada de dados de entrada
- Mudanças ou implementações feitas que são elegíveis devem constar no arquivo changelog se existir
- Tratamento de erros que não exponha informações
- Performance adequada para volume de dados de saúde
- Acessibilidade para usuários do sistema público
- Padronização de código: artefatos de propósito semelhante DEVEM seguir o mesmo padrão de estrutura, nomenclatura (classes, funções, parâmetros e retornos), tratamento de erros, logs, validações, métricas e testes.

ESPECÍFICOS POR CONTEXTO (aplicar conforme o PR):
— AIRFLOW:
- DAGs não interferem em processos críticos
- Dependências entre tasks bem definidas
- Retry logic adequado
- Logs não expõem dados sensíveis
- Compatibilidade com Oracle InstantClient

— API (Spring Boot):
- Endpoints protegidos (autenticação/autorização)
- Logs não expõem dados de pacientes
- DTOs adequados para response
- Paginação em listagens
- Tratamento de exceções sem expor stack traces

— DATABASE:
- Scripts SQL idempotentes
- Indexes para performance
- Constraints preservam integridade
- Scripts de rollback funcionais
- Não há dados hardcoded sensíveis
- Comentários adequados no schema

— FRONTEND (Vue.js):
- Componentes reutilizáveis e bem estruturados
- Estado gerenciado adequadamente (Vuex/Pinia)
- Não há dados sensíveis no storage
- Validação de formulários
- Feedback e loading states
- Tratamento de erros da API
- Performance (lazy loading, code splitting)
- Testes para componentes críticos
"""

[pr_description]
enable_pr_type = true
enable_pr_diagram = false
add_original_user_description = true
use_bullet_points = true
extra_instructions = """
CONTEXTO: Sistema REDS - Rede Estadual de Dados de Saúde.
Comece as frases com EDS no ínicio.

INCLUIR NA DESCRIÇÃO:
- Considerações de segurança e privacidade
- Impacto na performance do sistema

DOCUMENTAR PARA AIRFLOW:
- Impacto nos pipelines downstream
- Mudanças no schedule ou dependências
- Novos dados processados ou transformações
- Impacto na performance do ETL
- Compatibilidade com dados históricos

DOCUMENTAR PARA API (Spring boot):
- Novos endpoints ou mudanças existentes
- Mudanças no contrato de API
- Impacto na integração com frontend
- Considerações de segurança
- Performance esperada
- Breaking changes para clientes

DOCUMENTAR PARA DATABASE:
- Tabelas/colunas afetadas
- Estratégia de rollback
- Impacto na performance
- Dados que serão migrados
- Dependências com outras migrations
- Tempo estimado de execução

DOCUMENTAR PARA FRONTEND:
- Componentes novos ou modificados
- Mudanças na experiência do usuário
- Impacto na performance
- Compatibilidade com navegadores
- Acessibilidade implementada
- Integração com APIs
- Assets novos ou modificados
"""

[custom_labels."Frontend Vue.js"]
description = "Mudanças na interface Vue.js do sistema de visualização"

[custom_labels."API Spring Boot"]
description = "Mudanças na API Java/Spring Boot"

[custom_labels."Airflow ETL"]
description = "Mudanças nos pipelines de dados do Airflow"

[custom_labels."Database Migration"]
description = "Mudanças no esquema do banco via Flyway"

[custom_labels."REDS Critical"]
description = "Mudanças críticas no sistema REDS que afetam dados de saúde"

[custom_labels."Patient Data"]
description = "Mudanças que envolvem dados de pacientes - requer revisão de privacidade"

[custom_labels."Security Healthcare"]
description = "Mudanças relacionadas à segurança de dados de saúde"

[custom_labels."Performance ETL"]
description = "Otimizações de performance nos pipelines de dados"

[custom_labels."LGPD Compliance"]
description = "Mudanças relacionadas à conformidade com LGPD"

[custom_labels."ETL Pipeline"]
description = "Mudanças nos pipelines de ETL de dados de saúde"

[custom_labels."Data Quality"]
description = "Validações e qualidade de dados"

[custom_labels."API Endpoint"]
description = "Novos endpoints ou mudanças em endpoints existentes"

[custom_labels."Security API"]
description = "Mudanças relacionadas à segurança da API"

[custom_labels."Data Model"]
description = "Mudanças nos modelos de dados"

[custom_labels."Performance API"]
description = "Otimizações de performance na API"

[custom_labels."Schema Change"]
description = "Mudanças na estrutura do banco de dados"

[custom_labels."Data Migration"]
description = "Migração de dados existentes"

[custom_labels."Performance DB"]
description = "Otimizações de performance no banco"

[custom_labels."Rollback Safe"]
description = "Migration com estratégia de rollback segura"

[custom_labels."UI Component"]
description = "Novos componentes ou mudanças em componentes existentes"

[custom_labels."UX Improvement"]
description = "Melhorias na experiência do usuário"

[custom_labels."Accessibility"]
description = "Implementações de acessibilidade"

[custom_labels."Performance Frontend"]
description = "Otimizações de performance no frontend"
